### PR TITLE
Refactoring, more explicit plugins registering architecture. TODO: Ch…

### PR DESCRIPTION
**Pull request by tonkoandrew**
…ange documentation

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Please don't submit pull requests unsolicited, especially when dealing with this. pep8 doesn't want or need a plugin architecture and this has been discussed thoroughly in the past. It defers to flake8 to provide extensibility.

**Comment by tonkoandrew** [comment]
Ok, got it! I'm trying to reinvent the wheel :)

**Comment by sigmavirus24** [comment]
:+1: :)

**Comment by IanLee1521** [comment]
:) Also, just from a maintainer standpoint, I'm not sure there are many projects that would accept a commit / PR this big. If you look at [the files view](https://github.com/PyCQA/pep8/pull/445/files), GitHub can't even render the whole diff. :)

**Pull request closed without merging**
